version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.8.2
    steps:
      - checkout
      - run: |
          pip install --upgrade pip
          pip install -r requirements.txt
      - run: |
          flake8 .
          python -m pytest
